import { YouthProfile, TESDAProgram, SKAnnouncement, ReferralPipelineItem, SkillGapData, OfficialAccount, Councilor, Barangay } from "./types";

export const INITIAL_YOUTH_PROFILES: YouthProfile[] = [
  {
    id: "y-01",
    name: "Juan dela Cruz",
    age: 20,
    purok: "Purok 2",
    barangay: "Barangay San Sebastian",
    educationalAttainment: "College level",
    currentStatus: "Out-of-school",
    skills: ["Welding", "Metal fabrication", "Basic tools", "Blueprint reading"],
    interests: ["Vocational Training", "Employment"],
    sectorPreference: "Construction and Metals",
    livelihoodGoal: "Become a licensed welder and start own fabrication shop",
    contactNumber: "+63 917 123 4567",
    registeredDate: "June 15, 2026",
    matchScore: 94,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-02",
    name: "Maria Santos",
    age: 19,
    purok: "Purok 1",
    barangay: "Barangay San Sebastian",
    educationalAttainment: "SHS graduate",
    currentStatus: "Out-of-school",
    skills: ["Food processing", "Baking", "Customer service"],
    interests: ["Employment", "Entrepreneurship"],
    sectorPreference: "Tourism and Food",
    livelihoodGoal: "Work in a commercial bakery and eventually put up a custom cake business",
    contactNumber: "+63 918 234 5678",
    registeredDate: "June 16, 2026",
    matchScore: 87,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-03",
    name: "Carlo Reyes",
    age: 22,
    purok: "Purok 3",
    barangay: "Barangay San Sebastian",
    educationalAttainment: "HS graduate",
    currentStatus: "Out-of-school",
    skills: ["Basic computer", "Typing", "Data entry"],
    interests: ["Employment", "Vocational Training"],
    sectorPreference: "IT and Business Services",
    livelihoodGoal: "Get hired as an administrative clerk or encoder in a municipality office",
    contactNumber: "+63 919 345 6789",
    registeredDate: "June 16, 2026",
    matchScore: 61,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-04",
    name: "Liza Bautista",
    age: 17,
    purok: "Purok 4",
    barangay: "Barangay San Sebastian",
    educationalAttainment: "HS level",
    currentStatus: "Out-of-school",
    skills: ["Arts and crafts", "Sewing", "Design"],
    interests: ["Further Education", "Vocational Training"],
    sectorPreference: "Creative Arts",
    livelihoodGoal: "Establish a handmade garments brand and finish college",
    contactNumber: "+63 920 456 7890",
    registeredDate: "June 17, 2026",
    matchScore: 45,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-05",
    name: "Miguel Torres",
    age: 21,
    purok: "Purok 1",
    barangay: "Barangay San Sebastian",
    educationalAttainment: "HS graduate",
    currentStatus: "Out-of-school", // OSY
    skills: ["Carpentry", "Construction", "Masonry"],
    interests: ["Employment", "Vocational Training"],
    sectorPreference: "Construction and Metals",
    livelihoodGoal: "Be a building contractor and work on government infrastructure projects in San Luis",
    contactNumber: "+63 921 567 8901",
    registeredDate: "June 18, 2026",
    matchScore: 78,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-06",
    name: "Ana Garcia",
    age: 20,
    purok: "Purok 2",
    barangay: "Barangay San Sebastian",
    educationalAttainment: "College level",
    currentStatus: "Out-of-school",
    skills: ["Accounting", "Bookkeeping", "MS Excel", "Financial statement analysis"],
    interests: ["Employment", "Entrepreneurship"],
    sectorPreference: "IT and Business Services",
    livelihoodGoal: "Become a Certified Public Accountant or open a financial consulting firm",
    contactNumber: "+63 922 678 9012",
    registeredDate: "June 18, 2026",
    matchScore: 91,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-07",
    name: "Rico Mendoza",
    age: 23,
    purok: "Purok 3",
    barangay: "Barangay San Sebastian",
    educationalAttainment: "HS graduate",
    currentStatus: "Out-of-school",
    skills: ["Driving", "Motorcycle", "Delivery", "Basic engine repair"],
    interests: ["Employment", "Entrepreneurship"],
    sectorPreference: "Logistics and Transport",
    livelihoodGoal: "Set up a delivery franchise in Pampanga and obtain higher heavy equipment licenses",
    contactNumber: "+63 923 789 0123",
    registeredDate: "June 19, 2026",
    matchScore: 55,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-08",
    name: "Sofia Cruz",
    age: 18,
    purok: "Purok 4",
    barangay: "Barangay San Sebastian",
    educationalAttainment: "SHS graduate",
    currentStatus: "Out-of-school",
    skills: ["Cooking", "Catering", "Food safety"],
    interests: ["Vocational Training", "Entrepreneurship"],
    sectorPreference: "Tourism and Food",
    livelihoodGoal: "Run a catering business for local events and barangay assemblies",
    contactNumber: "+63 924 890 1234",
    registeredDate: "June 20, 2026",
    matchScore: 83,
    soloParent: true,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-09",
    name: "Ben Navarro",
    age: 24,
    purok: "Purok 2",
    barangay: "Barangay San Sebastian",
    educationalAttainment: "College level",
    currentStatus: "Out-of-school",
    skills: ["Programming", "HTML-CSS", "Graphic design", "Video editing"],
    interests: ["Employment", "Entrepreneurship"],
    sectorPreference: "IT and Business Services",
    livelihoodGoal: "Scale up freelance business to a digital agency hiring other San Luis youth",
    contactNumber: "+63 925 901 2345",
    registeredDate: "June 20, 2026",
    matchScore: 96,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-10",
    name: "Paolo Macapagal",
    age: 22,
    purok: "Purok 1",
    barangay: "Barangay San Agustin",
    educationalAttainment: "HS graduate",
    currentStatus: "Out-of-school",
    skills: ["Electrical wiring", "Basic plumbing", "Troubleshooting"],
    interests: ["Vocational Training", "Employment"],
    sectorPreference: "Construction and Metals",
    livelihoodGoal: "Work as a building electrician and gain NC II certification",
    contactNumber: "+63 926 123 4568",
    registeredDate: "June 21, 2026",
    matchScore: 88,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-11",
    name: "Althea Reyes",
    age: 18,
    purok: "Purok 3",
    barangay: "Barangay San Agustin",
    educationalAttainment: "SHS graduate",
    currentStatus: "Out-of-school",
    skills: ["Cooking", "Food preparation", "Customer relations"],
    interests: ["Employment"],
    sectorPreference: "Tourism and Food",
    livelihoodGoal: "Establish a community canteen serving healthy local dishes",
    contactNumber: "+63 927 234 5679",
    registeredDate: "June 22, 2026",
    matchScore: 82,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-12",
    name: "Christian David",
    age: 20,
    purok: "Purok 2",
    barangay: "Barangay San Agustin",
    educationalAttainment: "College level",
    currentStatus: "Out-of-school",
    skills: ["Graphic design", "Video editing", "Social media management"],
    interests: ["Entrepreneurship"],
    sectorPreference: "IT and Business Services",
    livelihoodGoal: "Run a remote freelance design services studio",
    contactNumber: "+63 928 345 6780",
    registeredDate: "June 22, 2026",
    matchScore: 75,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-13",
    name: "Jayson Castro",
    age: 21,
    purok: "Purok 4",
    barangay: "Barangay Santa Cruz Pambilog",
    educationalAttainment: "HS graduate",
    currentStatus: "Out-of-school",
    skills: ["Motorcycle repair", "Welding", "Manual labor"],
    interests: ["Vocational Training", "Employment"],
    sectorPreference: "Construction and Metals",
    livelihoodGoal: "Set up a local motorcycle diagnostic and repair shop",
    contactNumber: "+63 929 456 7891",
    registeredDate: "June 23, 2026",
    matchScore: 90,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-14",
    name: "Nicole Pineda",
    age: 19,
    purok: "Purok 2",
    barangay: "Barangay Santa Cruz Pambilog",
    educationalAttainment: "SHS graduate",
    currentStatus: "Out-of-school",
    skills: ["Baking", "Pastry decoration", "Basic inventory"],
    interests: ["Vocational Training", "Entrepreneurship"],
    sectorPreference: "Tourism and Food",
    livelihoodGoal: "Launch an online pastry business and supply local coffee shops",
    contactNumber: "+63 930 567 8902",
    registeredDate: "June 24, 2026",
    matchScore: 85,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-15",
    name: "Mark Anthony Soliman",
    age: 23,
    purok: "Purok 1",
    barangay: "Barangay Santa Cruz Pambilog",
    educationalAttainment: "College level",
    currentStatus: "Out-of-school",
    skills: ["Data entry", "MS Office", "Customer support"],
    interests: ["Employment"],
    sectorPreference: "IT and Business Services",
    livelihoodGoal: "Get a stable role in a BPO company or virtual assistant agency",
    contactNumber: "+63 931 678 9013",
    registeredDate: "June 24, 2026",
    matchScore: 70,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-16",
    name: "Princess Diaz",
    age: 20,
    purok: "Purok 1",
    barangay: "Barangay Santa Cruz Poblacion",
    educationalAttainment: "SHS graduate",
    currentStatus: "Out-of-school",
    skills: ["Nail art", "Hair styling", "Makeup application"],
    interests: ["Vocational Training", "Entrepreneurship"],
    sectorPreference: "Tourism and Food",
    livelihoodGoal: "Become an expert beautician and open a beauty salon in Poblacion",
    contactNumber: "+63 932 789 0124",
    registeredDate: "June 25, 2026",
    matchScore: 92,
    soloParent: false,
    pwd: true,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-17",
    name: "Kevin Tolentino",
    age: 24,
    purok: "Purok 3",
    barangay: "Barangay Santa Cruz Poblacion",
    educationalAttainment: "College level",
    currentStatus: "Out-of-school",
    skills: ["Computer networking", "Hardware troubleshooting", "Software installation"],
    interests: ["Employment"],
    sectorPreference: "IT and Business Services",
    livelihoodGoal: "Be employed as an IT support specialist or systems administrator",
    contactNumber: "+63 933 890 1235",
    registeredDate: "June 25, 2026",
    matchScore: 89,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-18",
    name: "Joshua Lagman",
    age: 22,
    purok: "Purok 2",
    barangay: "Barangay Santa Cruz Poblacion",
    educationalAttainment: "HS graduate",
    currentStatus: "Out-of-school",
    skills: ["Basic carpentry", "Masonry", "Painting"],
    interests: ["Vocational Training"],
    sectorPreference: "Construction and Metals",
    livelihoodGoal: "Acquire advanced metal welding skills and join civil construction works",
    contactNumber: "+63 934 901 2346",
    registeredDate: "June 26, 2026",
    matchScore: 80,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-19",
    name: "Camille Bondoc",
    age: 19,
    purok: "Purok 3",
    barangay: "Barangay Santa Lucia",
    educationalAttainment: "SHS graduate",
    currentStatus: "Out-of-school",
    skills: ["Bookkeeping", "Filing", "MS Word"],
    interests: ["Employment"],
    sectorPreference: "IT and Business Services",
    livelihoodGoal: "Serve as an office clerk or billing specialist",
    contactNumber: "+63 935 012 3457",
    registeredDate: "June 26, 2026",
    matchScore: 78,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-20",
    name: "Dave Mallari",
    age: 21,
    purok: "Purok 1",
    barangay: "Barangay Santa Lucia",
    educationalAttainment: "HS graduate",
    currentStatus: "Out-of-school",
    skills: ["Welding", "Metal cutting", "Power tool usage"],
    interests: ["Vocational Training"],
    sectorPreference: "Construction and Metals",
    livelihoodGoal: "Become an industrial welder with international trade certification",
    contactNumber: "+63 936 123 4569",
    registeredDate: "June 27, 2026",
    matchScore: 91,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-21",
    name: "Mary Grace Gomez",
    age: 23,
    purok: "Purok 2",
    barangay: "Barangay Santa Lucia",
    educationalAttainment: "College level",
    currentStatus: "Out-of-school",
    skills: ["Event coordination", "Creative writing", "Public speaking"],
    interests: ["Employment", "Entrepreneurship"],
    sectorPreference: "Tourism and Food",
    livelihoodGoal: "Develop local youth tourism programs and run a digital marketing company",
    contactNumber: "+63 937 234 5680",
    registeredDate: "June 27, 2026",
    matchScore: 84,
    soloParent: true,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-22",
    name: "Justin Calma",
    age: 20,
    purok: "Purok 4",
    barangay: "Barangay Santa Monica",
    educationalAttainment: "SHS graduate",
    currentStatus: "Out-of-school",
    skills: ["Baking", "Food packaging", "Customer service"],
    interests: ["Vocational Training", "Employment"],
    sectorPreference: "Tourism and Food",
    livelihoodGoal: "Become a pastry chef in a commercial kitchen",
    contactNumber: "+63 938 345 6781",
    registeredDate: "June 28, 2026",
    matchScore: 86,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-23",
    name: "Patrick Guintu",
    age: 22,
    purok: "Purok 1",
    barangay: "Barangay Santa Monica",
    educationalAttainment: "College level",
    currentStatus: "Out-of-school",
    skills: ["Basic programming", "Web design", "Database management"],
    interests: ["Employment"],
    sectorPreference: "IT and Business Services",
    livelihoodGoal: "Build automated systems and custom software for local cooperatives",
    contactNumber: "+63 939 456 7892",
    registeredDate: "June 28, 2026",
    matchScore: 93,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-24",
    name: "Aldrin Paras",
    age: 18,
    purok: "Purok 2",
    barangay: "Barangay Santa Monica",
    educationalAttainment: "HS graduate",
    currentStatus: "Out-of-school",
    skills: ["Carpentry", "Furniture assembly", "Basic sanding"],
    interests: ["Vocational Training"],
    sectorPreference: "Construction and Metals",
    livelihoodGoal: "Work in furniture manufacturing and learn computer-aided carpentry",
    contactNumber: "+63 940 567 8903",
    registeredDate: "June 29, 2026",
    matchScore: 80,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-25",
    name: "Ryan Lozano",
    age: 22,
    purok: "Purok 1",
    barangay: "Barangay Santo Tomas",
    educationalAttainment: "College level",
    currentStatus: "Out-of-school",
    skills: ["Graphic design", "Video editing", "Illustration"],
    interests: ["Employment", "Entrepreneurship"],
    sectorPreference: "IT and Business Services",
    livelihoodGoal: "Become a multimedia lead or creative director",
    contactNumber: "+63 941 678 9014",
    registeredDate: "June 29, 2026",
    matchScore: 88,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-26",
    name: "Ella Dimacali",
    age: 19,
    purok: "Purok 3",
    barangay: "Barangay Santo Tomas",
    educationalAttainment: "SHS graduate",
    currentStatus: "Out-of-school",
    skills: ["Tailoring", "Pattern drafting", "Embroidery"],
    interests: ["Vocational Training", "Entrepreneurship"],
    sectorPreference: "Tourism and Food",
    livelihoodGoal: "Open a boutique specializing in customized local garments",
    contactNumber: "+63 942 789 0125",
    registeredDate: "June 30, 2026",
    matchScore: 83,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-27",
    name: "Aaron Manansala",
    age: 21,
    purok: "Purok 2",
    barangay: "Barangay Santo Tomas",
    educationalAttainment: "HS graduate",
    currentStatus: "Out-of-school",
    skills: ["Electrical repair", "Plumbing", "Home appliance fix"],
    interests: ["Employment"],
    sectorPreference: "Construction and Metals",
    livelihoodGoal: "Establish an on-demand residential maintenance agency",
    contactNumber: "+63 943 890 1236",
    registeredDate: "June 30, 2026",
    matchScore: 87,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-28",
    name: "Chloe Halili",
    age: 20,
    purok: "Purok 2",
    barangay: "Barangay Santa Catalina",
    educationalAttainment: "College level",
    currentStatus: "Out-of-school",
    skills: ["Financial accounting", "Tax filing support", "MS Excel advanced"],
    interests: ["Employment"],
    sectorPreference: "IT and Business Services",
    livelihoodGoal: "Handle bookkeeping for local agricultural businesses",
    contactNumber: "+63 944 901 2347",
    registeredDate: "July 01, 2026",
    matchScore: 90,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-29",
    name: "Jervin Musni",
    age: 24,
    purok: "Purok 1",
    barangay: "Barangay Santa Catalina",
    educationalAttainment: "HS graduate",
    currentStatus: "Out-of-school",
    skills: ["Concrete mixing", "Plastering", "Metal scaffolding"],
    interests: ["Vocational Training", "Employment"],
    sectorPreference: "Construction and Metals",
    livelihoodGoal: "Work as a certified civil works foreman",
    contactNumber: "+63 945 012 3458",
    registeredDate: "July 01, 2026",
    matchScore: 82,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  },
  {
    id: "y-30",
    name: "Kimberly Sula",
    age: 18,
    purok: "Purok 3",
    barangay: "Barangay Santa Catalina",
    educationalAttainment: "SHS graduate",
    currentStatus: "Out-of-school",
    skills: ["Cooking", "Beverage preparation", "Customer service"],
    interests: ["Vocational Training", "Entrepreneurship"],
    sectorPreference: "Tourism and Food",
    livelihoodGoal: "Start a specialty cafe showcasing native Pampanga delicacies",
    contactNumber: "+63 946 123 4560",
    registeredDate: "July 02, 2026",
    matchScore: 88,
    soloParent: false,
    pwd: false,
    indigenous: false,
    hasReferred: false
  }
];

export const INITIAL_TESDA_PROGRAMS: TESDAProgram[] = [
  {
    id: "p-01",
    title: "Shielded Metal Arc Welding (SMAW) NC II",
    provider: "TESDA GPSAT (Gonzalo Puyat School of Arts and Trades)",
    type: "Training",
    location: "TESDA PTC, San Fernando, Pampanga",
    duration: "3 months (268 hours)",
    cost: "Free",
    slotsTotal: 30,
    slotsRemaining: 12,
    youthMatched: 8,
    eligibility: "High school graduate or SHS graduate; at least 15 years old; physically fit",
    contactPerson: "Engr. Danilo Santos",
    contactNumber: "+63 945 888 1122",
    activeStatus: "Active",
    requiredDocuments: [
      "PSA Birth Certificate (Original & Photocopy)",
      "4 copies of 1x1 Pictures (white background, collar, with name tag)",
      "High School Report Card / Form 137 or SHS Diploma",
      "Certificate of Barangay Residency (San Luis)",
      "Medical Certificate (Physically Fit)"
    ],
    classScheduleDays: "Mondays to Fridays",
    classScheduleTime: "8:00 AM - 12:00 PM",
    room: "Heavy Welding Shop - Bay A",
    instructor: "Engr. Danilo Santos, NC III",
    startDate: "July 15, 2026",
    endDate: "October 15, 2026"
  },
  {
    id: "p-02",
    title: "Food Processing NC II",
    provider: "TESDA GPSAT (Gonzalo Puyat School of Arts and Trades)",
    type: "Training",
    location: "San Luis Municipal Gym (Satellite Site)",
    duration: "2 months (180 hours)",
    cost: "Free",
    slotsTotal: 30,
    slotsRemaining: 0,
    youthMatched: 14,
    eligibility: "Katipunan ng Kabataan registered; resident of San Luis, Pampanga",
    contactPerson: "Ms. Evelyn Castor",
    contactNumber: "+63 932 777 3344",
    activeStatus: "Full",
    requiredDocuments: [
      "PSA Birth Certificate (Original & Photocopy)",
      "4 copies of 1x1 Pictures (white background, with name tag)",
      "High School Diploma or SHS Report Card",
      "Certificate of Barangay Residency (San Luis)",
      "Barangay Health Clearance"
    ],
    classScheduleDays: "Tuesdays and Thursdays",
    classScheduleTime: "1:00 PM - 5:00 PM",
    room: "San Luis Satellite Kitchen",
    instructor: "Ms. Evelyn Castor, LPT",
    startDate: "May 01, 2026",
    endDate: "June 01, 2026"
  },
  {
    id: "p-03",
    title: "Electrical Installation and Maintenance (EIM) NC II",
    provider: "TESDA GPSAT (Gonzalo Puyat School of Arts and Trades)",
    type: "Training",
    location: "TESDA PTC, San Fernando, Pampanga",
    duration: "4 months (402 hours)",
    cost: "Free",
    slotsTotal: 25,
    slotsRemaining: 17,
    youthMatched: 8,
    eligibility: "Completed basic secondary education; good color vision",
    contactPerson: "Mr. Jose Macapagal",
    contactNumber: "+63 916 222 5566",
    activeStatus: "Active",
    requiredDocuments: [
      "PSA Birth Certificate (Original & Photocopy)",
      "4 copies of 1x1 Pictures (white background, collar, with name tag)",
      "High School Diploma or Form 137",
      "Certificate of Barangay Residency (San Luis)",
      "Ishihara Eye Test Certificate (Good Color Vision)"
    ],
    classScheduleDays: "Mondays to Fridays",
    classScheduleTime: "1:00 PM - 5:00 PM",
    room: "Electrical Lab - Building B",
    instructor: "Mr. Jose Macapagal, REE",
    startDate: "July 20, 2026",
    endDate: "November 20, 2026"
  },
  {
    id: "p-04",
    title: "Housekeeping NC II",
    provider: "TESDA GPSAT (Gonzalo Puyat School of Arts and Trades)",
    type: "Training",
    location: "San Luis Livelihood Center",
    duration: "2 months (143 hours)",
    cost: "Free",
    slotsTotal: 30,
    slotsRemaining: 22,
    youthMatched: 5,
    eligibility: "At least Junior High School graduate or OSY",
    contactPerson: "Mrs. Gina David",
    contactNumber: "+63 927 444 6677",
    activeStatus: "Active",
    requiredDocuments: [
      "PSA Birth Certificate (Original & Photocopy)",
      "4 copies of 1x1 Pictures (white background)",
      "Junior High or SHS Diploma",
      "Certificate of Barangay Residency (San Luis)",
      "Barangay Clearance"
    ],
    classScheduleDays: "Saturdays and Sundays",
    classScheduleTime: "8:00 AM - 4:00 PM",
    room: "Simulated Suite Room 101",
    instructor: "Mrs. Gina David, HE Specialist",
    startDate: "August 15, 2026",
    endDate: "October 15, 2026"
  },
  {
    id: "p-05",
    title: "Bread and Pastry Production NC II",
    provider: "TESDA GPSAT (Gonzalo Puyat School of Arts and Trades)",
    type: "Training",
    location: "San Luis Municipal Gym (Kitchen Area)",
    duration: "2 months (141 hours)",
    cost: "Free",
    slotsTotal: 25,
    slotsRemaining: 8,
    youthMatched: 11,
    eligibility: "At least Junior High School graduate; can read and write",
    contactPerson: "Ms. Evelyn Castor",
    contactNumber: "+63 932 777 3344",
    activeStatus: "Active",
    requiredDocuments: [
      "PSA Birth Certificate (Original & Photocopy)",
      "4 copies of 1x1 Pictures (white background)",
      "Junior High School Report Card or Diploma",
      "Certificate of Barangay Residency (San Luis)",
      "Barangay Health Certificate"
    ],
    classScheduleDays: "Mondays and Wednesdays",
    classScheduleTime: "8:00 AM - 12:00 PM",
    room: "Pantry & Baking Section",
    instructor: "Ms. Evelyn Castor, LPT",
    startDate: "September 01, 2026",
    endDate: "November 01, 2026"
  },
  {
    id: "p-06",
    title: "Computer Systems Servicing NC II",
    provider: "TESDA GPSAT (Gonzalo Puyat School of Arts and Trades)",
    type: "Training",
    location: "San Luis High School Computer Lab",
    duration: "3 months (280 hours)",
    cost: "Free",
    slotsTotal: 30,
    slotsRemaining: 15,
    youthMatched: 7,
    eligibility: "Basic computer background is a plus, open to any KK member",
    contactPerson: "Mr. Ramil Cruz",
    contactNumber: "+63 909 333 4455",
    activeStatus: "Active",
    requiredDocuments: [
      "PSA Birth Certificate (Original & Photocopy)",
      "4 copies of 1x1 Pictures (white background)",
      "High School Diploma or College Report Card",
      "Certificate of Barangay Residency (San Luis)",
      "Barangay Clearance"
    ],
    classScheduleDays: "Mon, Wed, Fri",
    classScheduleTime: "9:00 AM - 12:00 PM",
    room: "Computer Science Lab 2",
    instructor: "Mr. Ramil Cruz, CSS Assessor",
    startDate: "July 10, 2026",
    endDate: "October 10, 2026"
  }
];

export const INITIAL_ANNOUNCEMENTS: SKAnnouncement[] = [
  {
    id: "a-01",
    title: "San Sebastian Annual Sports Fest 2026",
    body: "Ready your teams! The annual San Sebastian SK Sports Fest is opening registrations on June 25. Categories include Basketball (M/F), Volleyball, and E-sports. Contact your respective Purok youth coordinators to register.",
    category: "Program Update",
    audience: "All KK members",
    datePosted: "June 20, 2026",
    barangay: "San Sebastian"
  },
  {
    id: "a-02",
    title: "TESDA Welding NC II — Last 12 Slots Available",
    body: "We are organizing free transportation from Barangay San Sebastian to the TESDA GPSAT campus for the upcoming SMAW NC II class. Out-of-school youth will be prioritized for these final remaining slots. Generate your matching score and apply directly in your SiKap portal!",
    category: "Program Update",
    audience: "OSY only",
    datePosted: "June 18, 2026",
    barangay: "San Sebastian"
  },
  {
    id: "a-03",
    title: "San Sebastian Assembly — June 25, 2026",
    body: "All Katipunan ng Kabataan members of Barangay San Sebastian are invited to our general assembly and budget presentation on June 25, 5:00 PM at the Barangay Hall. Your inputs for the ABYIP budget allocation are highly appreciated.",
    category: "Reminder",
    audience: "All KK members",
    datePosted: "June 15, 2026",
    barangay: "San Sebastian"
  },
  {
    id: "a-04",
    title: "San Agustin Livelihood Seminar",
    body: "Barangay San Agustin SK is organizing a free livelihood seminar on local small business strategies and micro-finance opportunities on July 6, 2:00 PM at San Agustin Multipurpose Hall.",
    category: "Event",
    audience: "All KK members",
    datePosted: "June 28, 2026",
    barangay: "San Agustin"
  },
  {
    id: "a-05",
    title: "San Agustin TESDA Tourism & Bread-Baking Prep",
    body: "Calling all tourism and culinary enthusiasts in San Agustin! A pre-registration desk for Food and Beverage Services NC II will be open this Friday. Bring valid ID and high school diploma.",
    category: "Program Update",
    audience: "OSY only",
    datePosted: "June 27, 2026",
    barangay: "San Agustin"
  },
  {
    id: "a-06",
    title: "Santa Cruz Pambilog Food Cart Crafting Workshop",
    body: "Join our hands-on workshop on starting an online bakery or local food cart business. Free food-safe start-up containers and design blueprints will be provided to the first 25 registrants.",
    category: "Event",
    audience: "All KK members",
    datePosted: "June 29, 2026",
    barangay: "Santa Cruz Pambilog"
  },
  {
    id: "a-07",
    title: "Pambilog Motorcycle Diagnostic Initiative",
    body: "We are sponsoring the registration fees of 10 young mechanics for Advanced Engine Diagnosis and Repair courses. OSY in Pambilog who are currently doing manual repair works will have highest priority.",
    category: "Program Update",
    audience: "OSY only",
    datePosted: "June 28, 2026",
    barangay: "Santa Cruz Pambilog"
  },
  {
    id: "a-08",
    title: "Poblacion Computer Hardware Repair Program",
    body: "Want to learn custom PC building or diagnostic repairing? Barangay Santa Cruz Poblacion SK is launching a computer systems workshop. 15 slots open. Free toolkit provided to graduates.",
    category: "Program Update",
    audience: "All KK members",
    datePosted: "June 30, 2026",
    barangay: "Santa Cruz Poblacion"
  },
  {
    id: "a-09",
    title: "Santa Lucia Agri-Business Grant Application",
    body: "In partnership with the Municipal Agricultural Office, Santa Lucia SK is launching a micro-grant program for youth interested in organic urban farming. Submit business plans before July 10.",
    category: "Event",
    audience: "All KK members",
    datePosted: "June 28, 2026",
    barangay: "Santa Lucia"
  },
  {
    id: "a-10",
    title: "Santa Lucia Industrial Welder Scholarship",
    body: "Are you interested in high-demand construction metal fabrication? We are screening applicants for a fully-sponsored SMAW NC I/II scholarship batch. Apply now in your SiKap portal!",
    category: "Program Update",
    audience: "OSY only",
    datePosted: "June 27, 2026",
    barangay: "Santa Lucia"
  },
  {
    id: "a-11",
    title: "Santa Monica Pastry Baking Starter Kits",
    body: "Congratulations to the 12 graduates of our bread and pastry program! Santa Monica SK is distributing commercial mixer starter kits and oven accessories to help jumpstart your home bakeries.",
    category: "Reminder",
    audience: "All KK members",
    datePosted: "July 01, 2026",
    barangay: "Santa Monica"
  },
  {
    id: "a-12",
    title: "Santo Tomas Electronics Maintenance Training",
    body: "A free 5-day intensive crash course on consumer electronics repairs and smart home appliance fixing will start next Monday. Slots are limited to Santo Tomas youth members only.",
    category: "Program Update",
    audience: "All KK members",
    datePosted: "June 29, 2026",
    barangay: "Santo Tomas"
  },
  {
    id: "a-13",
    title: "Santa Catalina Bookkeeping Support Service",
    body: "Get hands-on training on advanced bookkeeping, tax filing support, and spreadsheets. Ideal for graduates and college-level out-of-school youth who want to offer freelance business services.",
    category: "Program Update",
    audience: "All KK members",
    datePosted: "July 02, 2026",
    barangay: "Santa Catalina"
  },
  {
    id: "a-14",
    title: "SiKap Municipal Demographics Update",
    body: "The municipal-wide KK demographic database is currently undergoing automated skills diagnostic matching using Gemini AI. Verify your contact details and active program pathways.",
    category: "General",
    audience: "All KK members",
    datePosted: "July 03, 2026"
  }
];

export const INITIAL_REFERRALS: ReferralPipelineItem[] = [
  {
    id: "ref-01",
    youthName: "Juan dela Cruz",
    purok: "Purok 2",
    barangay: "Barangay San Sebastian",
    programTitle: "Shielded Metal Arc Welding (SMAW) NC II",
    matchScore: 94,
    referralDate: "June 16, 2026",
    status: "Pending"
  },
  {
    id: "ref-02",
    youthName: "Maria Santos",
    purok: "Purok 1",
    barangay: "Barangay San Sebastian",
    programTitle: "Food Processing NC II",
    matchScore: 87,
    referralDate: "June 17, 2026",
    status: "Enrolled"
  },
  {
    id: "ref-03",
    youthName: "Ana Garcia",
    purok: "Purok 2",
    barangay: "Barangay San Sebastian",
    programTitle: "Computer Systems Servicing NC II",
    matchScore: 91,
    referralDate: "June 18, 2026",
    status: "Enrolled"
  },
  {
    id: "ref-04",
    youthName: "Miguel Torres",
    purok: "Purok 1",
    barangay: "Barangay San Sebastian",
    programTitle: "Electrical Installation and Maintenance (EIM) NC II",
    matchScore: 78,
    referralDate: "June 19, 2026",
    status: "Pending"
  }
];

export const SKILLS_GAPS: SkillGapData[] = [
  {
    skill: "Computer Literacy",
    count: 68,
    percentage: 16.2,
    availableSlots: 15,
    recommendedAction: "Organize Barangay-level digital tools and internet research basic workshop."
  },
  {
    skill: "Food Processing",
    count: 45,
    percentage: 10.7,
    availableSlots: 0,
    recommendedAction: "Fund additional localized batch of Food Processing NC II in municipal kitchen."
  },
  {
    skill: "Electrical Installation",
    count: 38,
    percentage: 9.0,
    availableSlots: 17,
    recommendedAction: "Refer out-of-school youth to empty training slots at TESDA GPSAT campus."
  },
  {
    skill: "Welding / Metal Fab",
    count: 32,
    percentage: 7.6,
    availableSlots: 12,
    recommendedAction: "Utilize SK budget to sponsor tools & protective gears for priority SMAW enrollees."
  },
  {
    skill: "Bread and Pastry",
    count: 24,
    percentage: 5.7,
    availableSlots: 8,
    recommendedAction: "Partner with local cooperative bakeries for job placement opportunities."
  }
];

export const INITIAL_BARANGAYS: Barangay[] = [
  { name: "San Agustin" },
  { name: "Santa Cruz Pambilog" },
  { name: "Santa Cruz Poblacion" },
  { name: "Santa Lucia" },
  { name: "Santa Monica" },
  { name: "Santo Tomas" },
  { name: "Santa Catalina" },
  { name: "San Sebastian" }
];

export const INITIAL_OFFICIALS: OfficialAccount[] = [
  {
    id: "o-01",
    name: "Rhea Cruz",
    email: "rhea.cruz@sanluispampanga.gov.ph",
    role: "SK Chairperson",
    barangay: "San Sebastian",
    status: "Active",
    dateCreated: "January 15, 2026"
  },
  {
    id: "o-02",
    name: "Danilo Santos",
    email: "danilo.santos@sanluispampanga.gov.ph",
    role: "Barangay Captain",
    barangay: "San Sebastian",
    status: "Active",
    dateCreated: "January 15, 2026"
  },
  {
    id: "o-03",
    name: "John Agustin",
    email: "john.agustin@sanluispampanga.gov.ph",
    role: "SK Chairperson",
    barangay: "San Agustin",
    status: "Active",
    dateCreated: "January 20, 2026"
  },
  {
    id: "o-04",
    name: "Jose Agustin",
    email: "jose.agustin@sanluispampanga.gov.ph",
    role: "Barangay Captain",
    barangay: "San Agustin",
    status: "Active",
    dateCreated: "January 20, 2026"
  },
  {
    id: "o-05",
    name: "Mark Cruz",
    email: "mark.cruz@sanluispampanga.gov.ph",
    role: "SK Chairperson",
    barangay: "Santa Cruz Pambilog",
    status: "Active",
    dateCreated: "February 01, 2026"
  },
  {
    id: "o-06",
    name: "Mario Cruz",
    email: "mario.cruz@sanluispampanga.gov.ph",
    role: "Barangay Captain",
    barangay: "Santa Cruz Pambilog",
    status: "Active",
    dateCreated: "February 01, 2026"
  },
  {
    id: "o-07",
    name: "Clara Cruz",
    email: "clara.cruz@sanluispampanga.gov.ph",
    role: "SK Chairperson",
    barangay: "Santa Cruz Poblacion",
    status: "Active",
    dateCreated: "February 02, 2026"
  },
  {
    id: "o-08",
    name: "Carlos Cruz",
    email: "carlos.cruz@sanluispampanga.gov.ph",
    role: "Barangay Captain",
    barangay: "Santa Cruz Poblacion",
    status: "Active",
    dateCreated: "February 02, 2026"
  },
  {
    id: "o-09",
    name: "Lucy Garcia",
    email: "lucy.garcia@sanluispampanga.gov.ph",
    role: "SK Chairperson",
    barangay: "Santa Lucia",
    status: "Active",
    dateCreated: "February 10, 2026"
  },
  {
    id: "o-10",
    name: "Luis Garcia",
    email: "luis.garcia@sanluispampanga.gov.ph",
    role: "Barangay Captain",
    barangay: "Santa Lucia",
    status: "Active",
    dateCreated: "February 10, 2026"
  },
  {
    id: "o-11",
    name: "Monica Castro",
    email: "monica.castro@sanluispampanga.gov.ph",
    role: "SK Chairperson",
    barangay: "Santa Monica",
    status: "Active",
    dateCreated: "February 15, 2026"
  },
  {
    id: "o-12",
    name: "Manuel Castro",
    email: "manuel.castro@sanluispampanga.gov.ph",
    role: "Barangay Captain",
    barangay: "Santa Monica",
    status: "Active",
    dateCreated: "February 15, 2026"
  },
  {
    id: "o-13",
    name: "Tomas Aquino",
    email: "tomas.aquino@sanluispampanga.gov.ph",
    role: "SK Chairperson",
    barangay: "Santo Tomas",
    status: "Active",
    dateCreated: "February 20, 2026"
  },
  {
    id: "o-14",
    name: "Timoteo Aquino",
    email: "timoteo.aquino@sanluispampanga.gov.ph",
    role: "Barangay Captain",
    barangay: "Santo Tomas",
    status: "Active",
    dateCreated: "February 20, 2026"
  },
  {
    id: "o-15",
    name: "Cathy Diaz",
    email: "cathy.diaz@sanluispampanga.gov.ph",
    role: "SK Chairperson",
    barangay: "Santa Catalina",
    status: "Active",
    dateCreated: "February 25, 2026"
  },
  {
    id: "o-16",
    name: "Christian Diaz",
    email: "christian.diaz@sanluispampanga.gov.ph",
    role: "Barangay Captain",
    barangay: "Santa Catalina",
    status: "Active",
    dateCreated: "February 25, 2026"
  },
  {
    id: "o-17",
    name: "Evelyn Castor",
    email: "evelyn.castor@tesda.gov.ph",
    role: "TESDA Representative",
    status: "Active",
    dateCreated: "March 01, 2026"
  }
];

export const INITIAL_COUNCILORS: Councilor[] = [
  {
    id: "c-01",
    name: "David Lim",
    email: "david.lim@sanluispampanga.gov.ph",
    role: "SK Councilor",
    status: "Active",
    dateCreated: "June 01, 2026",
    barangay: "San Sebastian"
  },
  {
    id: "c-02",
    name: "Sarah Perez",
    email: "sarah.perez@sanluispampanga.gov.ph",
    role: "Secretary",
    status: "Active",
    dateCreated: "June 02, 2026",
    barangay: "San Sebastian"
  },
  {
    id: "c-03",
    name: "James Bondoc",
    email: "james.bondoc@sanluispampanga.gov.ph",
    role: "Treasurer",
    status: "Inactive",
    dateCreated: "June 05, 2026",
    barangay: "San Sebastian"
  }
];

